@host = http://localhost:5000

@customerId = 2D751067-0F84-4AC6-B337-259DCA245073
@productId = 08D72FD5-EE3A-417A-93F2-3094CA5CD5B3
DELETE {{host}}/profile/customer/{{customerId}}/product/{{productId}}
Content-Type: application/json