export const USER_REGISTER_SUCCEED = 'USER_REGISTER_SUCCEED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const FETCH_USER_LOGIN = 'FETCH_USER_LOGIN';
export const FETCH_USER_LOGIN_GOOGLE = 'FETCH_USER_LOGIN_GOOGLE';
export const FETCH_USER_LOGIN_SUCCEED = 'FETCH_USER_LOGIN_SUCCEED';
export const FETCH_ADMIN_LOGIN = 'FETCH_ADMIN_LOGIN';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_LOGOUT = 'FETCH_USER_LOGOUT';
export const USER_REFRESH = 'USER_REFRESH';
export const USER_REGISTER_FINISH = 'USER_REGISTER_FINISH';
export const CREATE_CUSTOMER_PROFILE = 'CREATE_CUSTOMER_PROFILE';
export const CUSTOMER_PROFILE_EXITING = 'CUSTOMER_PROFILE_EXITING';

