export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_FAILED = "ADD_PRODUCTS_FAILED";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";
export const CREATE_ORDER_ONLINE = "CREATE_ORDER_ONLINE";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const PRODUCT_SAVE = "PRODUCT_SAVE";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const GET_NAME_CATEGORY = "GET_NAME_CATEGORY";
export const SEARCH_PRODUCT_ORDER_OFFLINE = "SEARCH_PRODUCT_ORDER_OFFLINE";
export const PRODUCT_DISCOUNT="PRODUCT_DISCOUNT";
export const PAID_SUCCESS="PAID_SUCCESS";
export const FETCH_PRODUCTS_FULL="FETCH_PRODUCTS_FULL";
export const SET_PAID_TYPE="SET_PAID_TYPE";
export const SAVE_IMAGE_UNITS="SAVE_IMAGE_UNITS";

